# ------------------------------------------------------------------------
# Copyright (c) 2022 megvii-model. All Rights Reserved.
# ------------------------------------------------------------------------
# Modified from BasicSR (https://github.com/xinntao/BasicSR)
# Copyright 2018-2020 BasicSR Authors
# ------------------------------------------------------------------------
# general settings
name: NAFNet-Artifact-width32
model_type: ImageRestorationModel
scale: 1
num_gpu: 1
manual_seed: 10

datasets:
  train:
    name: real-artifact-train
    type: PairedImageDataset
    dataroot_gt: ./datasets/real_artifact/train/gt
    dataroot_lq: ./datasets/real_artifact/train/lq

    filename_tmpl: '{}'
    io_backend:
      type: disk

    gt_size: 512    # Cropped patched size for gt patches.
    use_flip: true
    use_rot: true
    use_psf: false  # whether to use psf for degradation

    # data loader
    use_shuffle: true
    num_worker_per_gpu: 2
    batch_size_per_gpu: 2
    dataset_enlarge_ratio: 1
    prefetch_mode: ~

  val:
    name: real-artifact-val
    type: PairedImageDataset
    dataroot_gt: ./datasets/real_artifact/val/gt
    dataroot_lq: ./datasets/real_artifact/val/lq
    io_backend:
      type: disk

network_g:
  type: NAFNetLocal   # network name, see in models/archs/NAFNet_arch*.py
  width: 64
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 1e-3
    weight_decay: !!float 1e-3
    betas: [0.9, 0.9]

  scheduler:
    type: TrueCosineAnnealingLR
    T_max: 2000
    eta_min: !!float 1e-7

  total_iter: 2000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 200
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      type: calculate_psnr
      crop_border: 0
      test_y_channel: false
    ssim:
      type: calculate_ssim
      crop_border: 0
      test_y_channel: false

# logging settings
logger:
  print_freq: 5
  save_checkpoint_freq: !!float 500
  use_tb_logger: true
  wandb:
    project: ~
    resume_id: ~

# dist training settings
# dist_params:
#   backend: nccl
#   port: 29500
